### ISSUE TITLE
Ajustar algunos textos y funcionalidades relacionadas con idiomas

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/BioModelos.v2#243]
Revisar los archivos de internacionalización porque algunos mensajes no se están mostrando correctamente.

1. Hay que buscar que mensajes están ausentes tanto en inglés como en español
2. Hay que buscar los que sólo están en inglés y les fatla la traducción a español
3. En la caja "Contribuye" el botón del perfil dice "Profile Btn" y dice lo mismo en inglés (debería quitarse de btn en inglés)
4. Cambiar idioma también en los textos del mapa
5. Corregir el mensaje al guardar la edición de un modelo, actualmente es "Pause success"
6. Los mensajes de error relacionados con la foto del perfil en la página de editar usuario.

**Comment by erikasv** [comment]
Los punto 3, 5 y 6 fueron resueltos en [236](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biomodelos.v2/236)

**Comment by erikasv** [comment]
Los puntos pendientes ya no aplican porque la aplicación ha cambiado mucho desde que se identificaron.
