### ISSUE TITLE
Revisar el comportamiento del mapa y la caja de crear registro

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/BioModelos.v2#248]
En ventanas pequeñas, donde la caja de crear registro no se ve completamente, al cancelar la creación del registro hay un corrimiento del mapa hacia arriba. Este efecto se mantiene en las operaciones siguientes, por ejemplo si se vuelve a intentar crear un registro, el icono de ubicación se ve corrido, separado de la manito hacia arriba. La barra de latitud longitud y la atribución de leaflet también se mueve.

**Comment by erikasv** [comment]
Debido a que se realizó migración de la caja de creación de registro, este comportamiento ya no pasa.
