### ISSUE TITLE
Cambiar la forma de indicar los campos requeridos en la página de editar perfil

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/BioModelos.v2#251]
En la página de editar perfil, se debe buscar una forma más clara de indicar los campos requeridos (el * podría ser rojo) y verificar que hace que debajo del * hayan dos puntos (preferiblemente que no salgan)

**Comment by erikasv** [comment]
Esto fue corregido por Cesar en la tarea [236](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biomodelos.v2/236)
