### ISSUE TITLE
Ajustar la posicion del tooltip al agregar una tarea

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/BioModelos.v2#252]
El tooltip del botón agregar tarea está corrido (centrado en la tabla)

**Comment by erikasv** [comment]
Esto fue corregido por Cesar en la tarea [236](https://app.zenhub.com/workspaces/all-5f7f96a92b54ca00239a9348/issues/pem-humboldt/biomodelos.v2/236)
