### ISSUE TITLE
Validar con el equipo de Biomodelos que cuando se crea un registro no tiene "Nombre Original"

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/BioModelos.v2#254]
Validar con el equipo de Biomodelos que cuando se crea un registro no tiene "Nombre Original"

**Comment by erikasv** [comment]
De acuerdo a lo conversado con Helena, este comportamiento es correcto.

El campo `speciesOriginal` se usa para el nombre original de los registros de otras fuentes (como colecciones), porque puede pasar que el nombre venga con el autor u otras cosas, el campo `speciesOriginal` puede ser por ejemplo `"Anas bahamensis (Suárez, 1996)"`, de manera que no es necesario al crear el registro desde BioModelos.

Pero se debe cambiar el comportamiento de la caja de información de registro, el nombre de la especie que se muestra en el título debe corresponder al campo `acceptedNameUsage`. Esto se agregará a la tarea #306
