### ISSUE TITLE
Migrar alertas a Rails

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/BioModelos.v2#301]
En algunas partes de BioModelos se muestran alertas, como cuando se crea satisfactoriamente un registro, o cuando se entra al visor de un modelo y se informa al usuario que el modelo presentado es una hipótesis.

Estas alertas están implementadas en alertify, una librería de JavaScript, lo cual tiene 2 comportamientos que se desea cambiar: (1) Es una alerta del navegador, que bloquea la interacción con el sitio hasta cerrar la alerta, y (2) No están internacionalizadas, por lo que sólo se muestran en español. La solución a esos comportamientos es que ya no sean alertas del navegador sino mensajes flash (como el que aparece al iniciar sesión exitosamente).

Este cambio implica (a groso modo) estandarizar la forma en la que todo código javascript muestre esos mensajes, permitiendo la internacionalización de los mismos con los archivos de la gema I18n usada desde Rails (esto puede implicar la creación de más vistas de Rails y la migración del código desde archivos js a estas vistas)

También se desea que las alertas se puedan volver a mostrar al dar click en algún botón

#### Consideraciones
- La prioridad de esta migración (limitar el alcance de esta tarea a) son las alertas que aparecen cuando se carga una especie en el visor. (el estado del modelo)

**Comment by danflop** [comment]
@erikasv Es prioritario poder migrar especialmente las alertas que aparecen cuando se carga una especie en el visor de BioModelos. También es posible que se puedan volver a mostrar al hacer clic en algún botón.

**Comment by erikasv** [comment]
> @erikasv Es prioritario poder migrar especialmente las alertas que aparecen cuando se carga una especie en el visor de BioModelos. También es posible que se puedan volver a mostrar al hacer clic en algún botón.

Agregado a la descripción
