### ISSUE TITLE
Ajustes visuales

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/BioModelos.v2#324]
Realizar los siguientes ajustes de acuerdo a los comentarios del equipo temático para el próximo release:

1. Actualizar el texto de "Hipótesis disponibles". El nuevo texto es:
> Estas hipótesis corresponden al modelo aprobado en BioModelos (Validados), modelos publicados por usuarios (Publicados) o modelos estadísticos que han sido desarrollados de forma automatizada por el equipo de BioModelos (Estadísticos). Pueden ser calificadas por los miembros del grupo al que pertenece esta especie (Para calificar). Aquella con mayor calificación es la que se muestra por defecto. Puedes realizar la descarga de los modelos y consultar sus metadatos.
1. Dejar un poco más tiempo el mensaje del modelo inicial (configuración en esta [linea](https://github.com/PEM-Humboldt/BioModelos.v2/blob/develop/app/views/models/_model_status_info.html.erb#L12)) - Actualizar el tiempo deseado de acuerdo a lo que conteste el equipo
1. Traducir `ver más` y `ver menos` de la caja de información de registro
1. Traducir `Año` y `Categoría` de la caja de `registros y filtros`

**Comment by danflop** [comment]
@cazapatamar @erikasv Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/BioModelos.v2/324?planning-poker)
