### ISSUE TITLE
Eliminar "sin modelo" de la zona de estadísticas en home

### ISSUE THREAD

**Issue by valegrajales** [PEM-Humboldt/BioModelos.v2#82]
La zona de estadísticas no debe tener los datos de "sin modelo" en las gráficas estadísticas

**Comment by valegrajales** [comment]
Criterio de aceptación: Las gráficas de estadísticas solo debe tener información de "modelo en desarrollo" y "modelo validado"

**Comment by danflop** [comment]
Después de revisar el resultado de este cambio con Jorge y César, se considera que es mejor dejarlo pendiente para discusión, ya que no tiene mayor afectación sobre las funcionalidades principales de la plataforma.

**Comment by erikasv** [comment]
Hasta el momento no se ha tomado la decisión de cambiar esto.
